import 'dotenv/config';
import { connectDB } from './config/db.js';
import { Destination, Place, Viewpoint, Category } from './models/Content.js';
import User from './models/User.js';

await connectDB();

const img = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;

await Promise.all([
  Destination.deleteMany(),
  Place.deleteMany(),
  Viewpoint.deleteMany(),
  Category.deleteMany(),
]);

// ---------------- Categories ----------------
// Names match the frontend landing page icons and Explore filter chips.

const categories = await Category.insertMany(
  ['Mountains', 'Historical', 'Nature', 'Beaches', 'Viewpoints', 'Adventure', 'Food', 'Museums', 'Shopping'].map(
    (name) => ({ name, description: `Places, sights and experiences in the ${name} category.` })
  )
);
const category = (name) => categories.find((c) => c.name === name)?._id;

// ---------------- Destinations ----------------

const destinations = await Destination.insertMany([
  {
    name: 'Hunza',
    city: 'Karimabad',
    region: 'Gilgit-Baltistan',
    description: 'High valleys, apricot orchards and some of the most dramatic peaks on Earth, framed by the Karakoram.',
    tag: 'Hidden valley',
    featured: true,
    popularity: 96,
    images: [img('photo-1544735716-392fe2489ffa'), img('photo-1521292270410-a8c4d716d518')],
  },
  {
    name: 'Skardu',
    city: 'Skardu',
    region: 'Gilgit-Baltistan',
    description: 'Lakes, deserts and gateways to the Karakoram — a landscape of blues and golds.',
    tag: 'Karakoram gateway',
    featured: true,
    popularity: 94,
    images: [img('photo-1579033461380-adb47c3eb938'), img('photo-1500534623283-312aade485b7')],
  },
  {
    name: 'Nagar',
    city: 'Nagar',
    region: 'Gilgit-Baltistan',
    description: 'A quiet valley sitting face-to-face with the giant Rakaposhi massif.',
    tag: 'Rakaposhi views',
    popularity: 88,
    images: [img('photo-1464822759023-fed622ff2c3b'), img('photo-1447752875215-b2761acb3c5d')],
  },
  {
    name: 'Gilgit',
    city: 'Gilgit',
    region: 'Gilgit-Baltistan',
    description: 'The bustling crossroads of the north, where valleys, traders and cultures meet.',
    tag: 'Northern hub',
    popularity: 82,
    images: [img('photo-1501785888041-af3ef285b470'), img('photo-1469474968028-56623f02e42e')],
  },
  {
    name: 'Diamer',
    city: 'Chilas',
    region: 'Gilgit-Baltistan',
    description: 'Home to Fairy Meadows and the towering face of Nanga Parbat.',
    tag: 'Fairy meadows',
    featured: true,
    popularity: 90,
    images: [img('photo-1464278533981-50106e6176b1'), img('photo-1441974231531-c6227db76b6e')],
  },
  {
    name: 'Lahore',
    city: 'Lahore',
    region: 'Punjab',
    description: 'A historic city of gardens, forts, food streets and Mughal landmarks.',
    tag: 'Historic capital',
    featured: true,
    popularity: 95,
    images: [img('photo-1564507592333-c60657eea523'), img('photo-1529676468696-f3a47aba7d5c')],
  },
  {
    name: 'Islamabad',
    city: 'Islamabad',
    region: 'Capital Territory',
    description: 'A green, orderly capital framed by the Margalla Hills.',
    tag: 'Capital city',
    featured: true,
    popularity: 90,
    images: [img('photo-1518005020951-eccb494ad742'), img('photo-1480714378408-67cf0d13bc1b')],
  },
  {
    name: 'Murree',
    city: 'Murree',
    region: 'Punjab',
    description: 'A cool hill station of pine forests, mountain air and winding bazaars.',
    tag: 'Hill station',
    popularity: 80,
    images: [img('photo-1507525428034-b723cf961d3e'), img('photo-1447752875215-b2761acb3c5d')],
  },
  {
    name: 'Karachi',
    city: 'Karachi',
    region: 'Sindh',
    description: 'A sprawling seaside metropolis where beaches meet street food and history.',
    tag: 'Seaside metropolis',
    popularity: 86,
    images: [img('photo-1505118380757-91f5f5632de0'), img('photo-1524661135-423995f22d0b')],
  },
]);
const destination = (name) => destinations.find((d) => d.name === name)._id;

// ---------------- Places ----------------

const places = await Place.insertMany([
  {
    name: 'Attabad Lake',
    destination: destination('Hunza'),
    category: category('Nature'),
    type: 'Place',
    tag: 'Popular',
    description: 'Impossible turquoise water surrounded by some of the Karakoram’s most dramatic peaks.',
    location: 'Gojal, Hunza',
    rating: 4.9,
    reviewCount: 284,
    popularity: 97,
    featured: true,
    openingHours: 'Daily · 08:00 AM – 06:00 PM',
    entryFee: 100,
    recommendedVisitingTime: 'Golden hour',
    estimatedDuration: '2–3 hours',
    images: [img('photo-1544735716-392fe2489ffa')],
  },
  {
    name: 'Baltit Fort',
    destination: destination('Hunza'),
    category: category('Historical'),
    type: 'Place',
    tag: 'Heritage',
    description: 'A centuries-old fort overlooking Karimabad and the valley beyond.',
    location: 'Karimabad, Hunza',
    rating: 4.8,
    reviewCount: 210,
    popularity: 92,
    featured: true,
    openingHours: 'Daily · 09:00 AM – 05:00 PM',
    entryFee: 800,
    recommendedVisitingTime: 'Morning',
    estimatedDuration: '1–2 hours',
    images: [img('photo-1564507592333-c60657eea523')],
  },
  {
    name: 'Altit Fort',
    destination: destination('Hunza'),
    category: category('Historical'),
    type: 'Place',
    tag: 'Heritage',
    description: 'One of the oldest forts in the region, perched above the river at Altit.',
    location: 'Altit, Hunza',
    rating: 4.7,
    reviewCount: 164,
    popularity: 84,
    openingHours: 'Daily · 09:00 AM – 05:00 PM',
    entryFee: 500,
    recommendedVisitingTime: 'Morning',
    estimatedDuration: '1–2 hours',
    images: [img('photo-1528723166434-2b260b54e477')],
  },
  {
    name: 'Passu Cones',
    destination: destination('Hunza'),
    category: category('Mountains'),
    type: 'Place',
    tag: 'Iconic',
    description: 'Sharp, unforgettable peaks rising above the quiet village of Passu.',
    location: 'Passu, Hunza',
    rating: 4.9,
    reviewCount: 198,
    popularity: 95,
    featured: true,
    recommendedVisitingTime: 'Sunset',
    estimatedDuration: '1 hour',
    images: [img('photo-1521292270410-a8c4d716d518')],
  },
  {
    name: 'Shangrila Lake',
    destination: destination('Skardu'),
    category: category('Nature'),
    type: 'Place',
    tag: 'Popular',
    description: 'A calm, pear-shaped lake inside the Shangrila resort complex.',
    location: 'Skardu',
    rating: 4.6,
    reviewCount: 142,
    popularity: 82,
    openingHours: 'Daily · 08:00 AM – 08:00 PM',
    entryFee: 200,
    recommendedVisitingTime: 'Morning',
    estimatedDuration: '1–2 hours',
    images: [img('photo-1500534623283-312aade485b7')],
  },
  {
    name: 'Katpana Cold Desert',
    destination: destination('Skardu'),
    category: category('Nature'),
    type: 'Place',
    tag: 'Unique',
    description: 'A high-altitude cold desert at the edge of the Karakoram mountains.',
    location: 'Skardu',
    rating: 4.7,
    reviewCount: 121,
    popularity: 80,
    recommendedVisitingTime: 'Late afternoon',
    estimatedDuration: '1–2 hours',
    images: [img('photo-1579033461380-adb47c3eb938')],
  },
  {
    name: 'Rakaposhi Viewpoint',
    destination: destination('Nagar'),
    category: category('Viewpoints'),
    type: 'Place',
    tag: 'Must see',
    description: 'One of the closest, most breathtaking views of Rakaposhi’s 7,788-metre face.',
    location: 'Ghulmet, Nagar',
    rating: 4.8,
    reviewCount: 176,
    popularity: 89,
    recommendedVisitingTime: 'Sunrise',
    estimatedDuration: '1 hour',
    images: [img('photo-1464822759023-fed622ff2c3b')],
  },
  {
    name: 'Fairy Meadows',
    destination: destination('Diamer'),
    category: category('Mountains'),
    type: 'Place',
    tag: 'Iconic',
    description: 'A grassy plateau beneath Nanga Parbat, reached by jeep and a long trek.',
    location: 'Diamer',
    rating: 4.9,
    reviewCount: 233,
    popularity: 96,
    featured: true,
    recommendedVisitingTime: 'Summer · June–September',
    estimatedDuration: 'Full day',
    images: [img('photo-1464278533981-50106e6176b1')],
  },
  {
    name: 'Lahore Fort',
    destination: destination('Lahore'),
    category: category('Historical'),
    type: 'Place',
    tag: 'Heritage',
    description: 'A Mughal-era citadel in the heart of the old city.',
    location: 'Walled City, Lahore',
    rating: 4.8,
    reviewCount: 302,
    popularity: 92,
    featured: true,
    openingHours: 'Daily · 08:30 AM – 05:00 PM',
    entryFee: 1000,
    recommendedVisitingTime: 'Morning',
    estimatedDuration: '2–3 hours',
    images: [img('photo-1564507592333-c60657eea523')],
  },
  {
    name: 'Badshahi Mosque',
    destination: destination('Lahore'),
    category: category('Historical'),
    type: 'Place',
    tag: 'Heritage',
    description: 'Monumental Mughal mosque beside Lahore Fort, a masterpiece of red sandstone.',
    location: 'Walled City, Lahore',
    rating: 4.9,
    reviewCount: 287,
    popularity: 94,
    openingHours: 'Daily · 08:00 AM – 08:00 PM',
    entryFee: 0,
    recommendedVisitingTime: 'Sunset',
    estimatedDuration: '1 hour',
    images: [img('photo-1529676468696-f3a47aba7d5c')],
  },
  {
    name: 'Minar-e-Pakistan',
    destination: destination('Lahore'),
    category: category('Historical'),
    type: 'Place',
    tag: 'Monument',
    description: 'National monument in Iqbal Park, marking the site of the 1940 resolution.',
    location: 'Iqbal Park, Lahore',
    rating: 4.7,
    reviewCount: 158,
    popularity: 86,
    openingHours: 'Daily · 09:00 AM – 06:00 PM',
    entryFee: 50,
    recommendedVisitingTime: 'Evening',
    estimatedDuration: '1 hour',
    images: [img('photo-1512453979798-5ea266f8880c')],
  },
  {
    name: 'Anarkali Food Street',
    destination: destination('Lahore'),
    category: category('Food'),
    type: 'Place',
    tag: 'Street food',
    description: 'A chaotic, delicious stretch of Lahori classics and late-night kebabs.',
    location: 'Anarkali Bazaar, Lahore',
    rating: 4.6,
    reviewCount: 204,
    popularity: 88,
    openingHours: 'Daily · 04:00 PM – 01:00 AM',
    entryFee: 0,
    recommendedVisitingTime: 'Night',
    estimatedDuration: '2 hours',
    images: [img('photo-1414235077428-338989a2e8c0')],
  },
  {
    name: 'Rohtas Fort',
    destination: destination('Islamabad'),
    category: category('Historical'),
    type: 'Place',
    tag: 'UNESCO',
    description: 'A massive 16th-century fortress carved into the hills near Jhelum.',
    location: 'Jhelum Road',
    rating: 4.7,
    reviewCount: 137,
    popularity: 81,
    openingHours: 'Daily · 09:00 AM – 06:00 PM',
    entryFee: 500,
    recommendedVisitingTime: 'Morning',
    estimatedDuration: '2–3 hours',
    images: [img('photo-1564507592333-c60657eea523')],
  },
  {
    name: 'Daman-e-Koh',
    destination: destination('Islamabad'),
    category: category('Viewpoints'),
    type: 'Place',
    tag: 'Popular',
    description: 'A hilltop viewpoint over the capital with sweeping Margalla views.',
    location: 'Margalla Hills, Islamabad',
    rating: 4.5,
    reviewCount: 188,
    popularity: 84,
    openingHours: 'Daily · 08:00 AM – 10:00 PM',
    entryFee: 50,
    recommendedVisitingTime: 'Sunset',
    estimatedDuration: '1–2 hours',
    images: [img('photo-1480714378408-67cf0d13bc1b')],
  },
  {
    name: 'Faisal Mosque',
    destination: destination('Islamabad'),
    category: category('Museums'),
    type: 'Place',
    tag: 'Landmark',
    description: 'A striking modern mosque set against the Margalla Hills.',
    location: 'Islamabad',
    rating: 4.8,
    reviewCount: 259,
    popularity: 91,
    openingHours: 'Daily · 08:00 AM – 10:00 PM',
    entryFee: 0,
    recommendedVisitingTime: 'Morning',
    estimatedDuration: '1 hour',
    images: [img('photo-1518005020951-eccb494ad742')],
  },
  {
    name: 'Kashmir Point',
    destination: destination('Murree'),
    category: category('Viewpoints'),
    type: 'Place',
    tag: 'Scenic',
    description: 'A quiet viewpoint offering long views over the Murree hills.',
    location: 'Murree',
    rating: 4.4,
    reviewCount: 112,
    popularity: 76,
    openingHours: 'Daily · 09:00 AM – 06:00 PM',
    entryFee: 0,
    recommendedVisitingTime: 'Golden hour',
    estimatedDuration: '1 hour',
    images: [img('photo-1447752875215-b2761acb3c5d')],
  },
  {
    name: 'Ghari Road Hike',
    destination: destination('Murree'),
    category: category('Adventure'),
    type: 'Place',
    tag: 'Active',
    description: 'A pleasant woodland trail above the town, perfect for a slow walk.',
    location: 'Murree',
    rating: 4.3,
    reviewCount: 96,
    popularity: 72,
    recommendedVisitingTime: 'Morning',
    estimatedDuration: '2–3 hours',
    images: [img('photo-1507525428034-b723cf961d3e')],
  },
  {
    name: 'Clifton Beach',
    destination: destination('Karachi'),
    category: category('Beaches'),
    type: 'Place',
    tag: 'City beach',
    description: 'Karachi’s classic seaside stretch with camel rides and sunset crowds.',
    location: 'Clifton, Karachi',
    rating: 4.2,
    reviewCount: 178,
    popularity: 78,
    openingHours: 'Daily · 06:00 AM – 11:00 PM',
    entryFee: 0,
    recommendedVisitingTime: 'Sunset',
    estimatedDuration: '2 hours',
    images: [img('photo-1505118380757-91f5f5632de0')],
  },
  {
    name: 'Mohatta Palace',
    destination: destination('Karachi'),
    category: category('Museums'),
    type: 'Place',
    tag: 'Heritage',
    description: 'A pink sandstone museum palace by the sea, full of Karachi history.',
    location: 'Clifton, Karachi',
    rating: 4.5,
    reviewCount: 121,
    popularity: 74,
    openingHours: 'Tue–Sun · 10:00 AM – 06:00 PM',
    entryFee: 100,
    recommendedVisitingTime: 'Afternoon',
    estimatedDuration: '1–2 hours',
    images: [img('photo-1524661135-423995f22d0b')],
  },
  {
    name: 'Mall Road Shops',
    destination: destination('Karachi'),
    category: category('Shopping'),
    type: 'Place',
    tag: 'Shopping',
    description: 'A lively strip of fabric, craft and souvenir stalls in the city centre.',
    location: 'Saddar, Karachi',
    rating: 4.1,
    reviewCount: 88,
    popularity: 68,
    openingHours: 'Daily · 11:00 AM – 10:00 PM',
    entryFee: 0,
    recommendedVisitingTime: 'Evening',
    estimatedDuration: '2 hours',
    images: [img('photo-1441986300917-64674bd600d8')],
  },
]);

const place = (name) => places.find((p) => p.name === name)._id;

// ---------------- Viewpoints ----------------

await Viewpoint.insertMany([
  {
    name: "Eagle's Nest",
    destination: destination('Hunza'),
    category: category('Mountains'),
    description: 'A high viewpoint above Duikar where the whole Hunza valley unfolds below.',
    rating: 4.9,
    reviewCount: 328,
    bestTime: 'Sunrise',
    elevation: '2,800m',
    featured: true,
    popularity: 98,
    nearbyPlaces: [place('Altit Fort'), place('Baltit Fort')],
    images: [img('photo-1589553416260-f586c8f1514f')],
  },
  {
    name: 'Passu Viewpoint',
    destination: destination('Hunza'),
    category: category('Viewpoints'),
    description: 'Sharp peaks and the turquoise river from the road above Passu.',
    rating: 4.8,
    reviewCount: 214,
    bestTime: 'Golden hour',
    elevation: '2,300m',
    featured: true,
    popularity: 93,
    nearbyPlaces: [place('Passu Cones'), place('Attabad Lake')],
    images: [img('photo-1464822759023-fed622ff2c3b')],
  },
  {
    name: 'Rakaposhi View',
    destination: destination('Nagar'),
    category: category('Mountains'),
    description: 'The great face of Rakaposhi lit by the late evening sun.',
    rating: 4.9,
    reviewCount: 246,
    bestTime: 'Sunset',
    elevation: '2,100m',
    featured: true,
    popularity: 95,
    nearbyPlaces: [place('Rakaposhi Viewpoint')],
    images: [img('photo-1447752875215-b2761acb3c5d')],
  },
  {
    name: 'Nanga Parbat View',
    destination: destination('Diamer'),
    category: category('Mountains'),
    description: 'The killer mountain looming over the plains of Chilas.',
    rating: 4.8,
    reviewCount: 167,
    bestTime: 'Sunrise',
    elevation: '2,400m',
    popularity: 88,
    nearbyPlaces: [place('Fairy Meadows')],
    images: [img('photo-1464278533981-50106e6176b1')],
  },
  {
    name: 'Deosai Plateau',
    destination: destination('Skardu'),
    category: category('Nature'),
    description: 'A rolling high-altitude plateau, often called the land of giants.',
    rating: 4.8,
    reviewCount: 191,
    bestTime: 'June–September',
    elevation: '4,114m',
    featured: true,
    popularity: 91,
    nearbyPlaces: [place('Shangrila Lake'), place('Katpana Cold Desert')],
    images: [img('photo-1500534623283-312aade485b7')],
  },
  {
    name: 'Gol National Park',
    destination: destination('Gilgit'),
    category: category('Nature'),
    description: 'Forests and views just a short drive from Gilgit town.',
    rating: 4.5,
    reviewCount: 88,
    bestTime: 'Morning',
    elevation: '1,900m',
    popularity: 74,
    images: [img('photo-1441974231531-c6227db76b6e')],
  },
  {
    name: 'Kargah Buddha',
    destination: destination('Gilgit'),
    category: category('Historical'),
    description: 'Ancient rock carvings and a seated Buddha outside the city.',
    rating: 4.3,
    reviewCount: 74,
    bestTime: 'Afternoon',
    elevation: '1,800m',
    popularity: 70,
    images: [img('photo-1528723166434-2b260b54e477')],
  },
  {
    name: 'Attabad Lake View',
    destination: destination('Hunza'),
    category: category('Nature'),
    description: 'The classic turquoise view from the road above Attabad.',
    rating: 4.7,
    reviewCount: 155,
    bestTime: 'Golden hour',
    elevation: '1,600m',
    popularity: 86,
    nearbyPlaces: [place('Attabad Lake')],
    images: [img('photo-1544735716-392fe2489ffa')],
  },
  {
    name: 'Margalla Viewpoint',
    destination: destination('Islamabad'),
    category: category('Viewpoints'),
    description: 'A city viewpoint over the green capital at dusk.',
    rating: 4.5,
    reviewCount: 132,
    bestTime: 'Sunset',
    elevation: '1,500m',
    popularity: 79,
    nearbyPlaces: [place('Daman-e-Koh')],
    images: [img('photo-1480714378408-67cf0d13bc1b')],
  },
]);

// ---------------- Admin user ----------------

await User.findOneAndUpdate(
  { email: 'admin@wanderlens.local' },
  {
    name: 'WanderLens Admin',
    email: 'admin@wanderlens.local',
    password: 'Admin12345!',
    role: 'admin',
  },
  { upsert: true, setDefaultsOnInsert: true }
);

console.log('Seed complete.');
console.log(`  Categories: ${categories.length}`);
console.log(`  Destinations: ${destinations.length}`);
console.log(`  Places: ${places.length}`);
console.log('  Admin: admin@wanderlens.local / Admin12345!');

process.exit(0);